name: DeployToAWSS3
 
on:
  push:
    branches:
      - main

 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

 
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
 
 
    - name: Deploy to S3 🚀
      uses: jakejarvis/s3-sync-action@main
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'wwwroot'      # optional: defaults to entire repository
